// ===== PFG Chapati - COMPLETE PRODUCTION SCRIPT =====
// WITH EMAIL/PASSWORD AUTHENTICATION
// ====================================================

(function() {
    'use strict';

    // -------------------- FIREBASE CONFIG --------------------
    const firebaseConfig = {
        apiKey: "AIzaSyAGyOqUe-t04O2M6cU6Iqg8MV4V8S_a_mk",
        authDomain: "pfg-chapati.firebaseapp.com",
        projectId: "pfg-chapati",
        storageBucket: "pfg-chapati.firebasestorage.app",
        messagingSenderId: "903359666880",
        appId: "1:903359666880:web:3f0c4e659a97336b40eb25",
        measurementId: "G-241GDRBG8N"
    };

    firebase.initializeApp(firebaseConfig);
    const auth = firebase.auth();
    const db = firebase.firestore();

    // -------------------- GLOBAL VARIABLES --------------------
    let currentUser = null;
    let userRole = null;
    let cart = [];
    let rewards = { points: 0, beansCount: 0 };
    let userLocation = null;
    let currentLang = 'en';
    let isCartOpen = false;
    let map = null;
    let riderMarker = null;
    let orderListener = null;
    let menuItems = [];
    let vendors = [];
    let riderOnline = false;

    const elements = {};

    // -------------------- TRANSLATIONS (ENGLISH) --------------------
    const translations = {
        en: {
            site_name: 'PFG Chapati',
            home: 'Home', menu: 'Menu', why: 'Why PFG', vendors: 'Vendors',
            rider_dashboard: 'Rider Dashboard', vendor_dashboard: 'Vendor Dashboard',
            my_orders: 'My Orders', login: 'Login', logout: 'Logout',
            profile: 'Profile', settings: 'Settings', order_now: 'Order Now',
            hero_title: 'Fresh Chapatis Delivered in 10 Minutes',
            hero_subtitle: 'Order delicious, hot chapatis from anywhere in Kampala and get them delivered to your doorstep in just 10 minutes!',
            why_title: 'Why Choose PFG Chapati?',
            feature1_title: '10-Minute Delivery',
            feature1_desc: 'We guarantee delivery within 10 minutes anywhere in Kampala. Fresh and hot!',
            feature2_title: 'Fresh Ingredients',
            feature2_desc: 'We connect you with makers who use only the freshest ingredients.',
            feature3_title: 'Free Delivery',
            feature3_desc: 'Free delivery on orders above 10,000 UGX. No hidden charges.',
            feature4_title: 'Variety of Options',
            feature4_desc: 'From plain chapati to rolex and rolipizza – we have it all.',
            our_menu: 'Our Menu', breakfast: 'Breakfast', lunch: 'Lunch',
            dinner: 'Dinner', drinks: 'Drinks',
            find_vendors: 'Find Trusted Chapati Makers in Kampala',
            vendors_sub: 'Fresh, hot, and ready — connect with the best local vendors near you.',
            detect_location: 'Detect my location', search: 'Search',
            your_cart: 'Your Cart', subtotal: 'Subtotal', discount: 'Discount',
            delivery_fee: 'Delivery Fee', total: 'Total',
            checkout: 'Proceed to Checkout', whatsapp_order: 'Order via WhatsApp',
            call_now: 'Call Now', add_to_cart: 'Add to Cart',
            added_to_cart: '{name} added to cart!', empty_cart: 'Your cart is empty',
            delivery_details: 'Delivery Details', payment_method: 'Payment Method',
            cash_on_delivery: 'Cash on Delivery', mobile_money: 'Mobile Money',
            credit_card: 'Credit Card', place_order: 'Place Order',
            order_placed: 'Order placed successfully!', order_failed: 'Failed to place order',
            login_required: 'Please login first', fill_details: 'Please fill in all required fields',
            points_earned: 'You have {points} points ({beansCount} Kikomando orders)',
            redeem: 'Redeem 100 points for 1000 UGX off', discount_applied: 'Discount applied at checkout!',
            status_pending: 'Pending', status_assigned: 'Assigned', status_delivered: 'Delivered',
            accept: 'Accept', mark_delivered: 'Mark Delivered', today_earnings: 'Today\'s Earnings',
            total_earnings: 'Total Earnings', deliveries_today: 'Deliveries Today',
            rating: 'Rating', assigned_orders: 'Assigned Orders', delivery_history: 'Delivery History',
            recent_orders: 'Recent Orders', pending_orders: 'Pending Orders',
            today_orders: 'Today\'s Orders', total_sales: 'Total Sales',
            average_rating: 'Average Rating', update_menu: 'Update Menu',
            view_reviews: 'View Reviews', earnings_report: 'Earnings Report',
            full_name: 'Full Name', phone_number: 'Phone Number', email: 'Email',
            default_address: 'Default Delivery Address', save_changes: 'Save Changes',
            change_photo: 'Change Photo', business_info: 'Business Information',
            business_name: 'Business Name', business_address: 'Business Address',
            business_hours: 'Business Hours', vehicle_info: 'Vehicle Information',
            vehicle_type: 'Vehicle Type', license_plate: 'License Plate',
            notifications: 'Notifications', push_notifications: 'Push Notifications',
            sms_notifications: 'SMS Notifications', email_notifications: 'Email Notifications',
            language: 'Language', payment_methods: 'Payment Methods',
            privacy_security: 'Privacy & Security', change_password: 'Change Password',
            delete_account: 'Delete Account', quick_links: 'Quick Links',
            contact: 'Contact', privacy: 'Privacy Policy', terms: 'Terms of Service',
            cookies: 'Cookie Policy',
            footer_desc: 'Bridging snack centers and customers in Kampala with a 10-minute guarantee.',
            download_app: 'Download App', all_orders: 'All Orders',
            cancelled: 'Cancelled', track_order: 'Track Your Order',
            rider_location: 'Rider Location', preparing: 'Preparing',
            out_for_delivery: 'Out for Delivery', delivered: 'Delivered',
            accepted: 'Accepted', offline: 'Offline', online: 'Online',
            customer: 'Customer', rider: 'Rider', vendor: 'Vendor',
            save: 'Save', km_away: '{distance} km away',
            location_detected: 'Location detected!', location_failed: 'Unable to detect location',
            login_email: 'Login with Email', signup: 'Sign Up',
            confirm_password: 'Confirm Password', forgot_password: 'Forgot Password?',
            reset_password: 'Reset Password', no_account: 'Don\'t have an account? Sign Up',
            have_account: 'Already have an account? Login',
            password_mismatch: 'Passwords do not match', login_success: 'Logged in successfully!',
            signup_success: 'Account created successfully!', reset_email_sent: 'Password reset email sent. Check your inbox.',
            auth_modal_title: 'Login / Sign Up', close: 'Close',
            verify_email: 'Please verify your email before logging in.',
            reset_instructions: 'Enter your email to receive a password reset link.',
            add_item: 'Add Item', edit_item: 'Edit Item', delete_item: 'Delete Item',
            item_name: 'Item Name', item_description: 'Description', item_price: 'Price',
            item_category: 'Category', item_image: 'Image URL',
            go_online: 'Go Online', go_offline: 'Go Offline',
            accept_order: 'Accept Order', order_accepted: 'Order accepted',
            order_delivered: 'Order marked as delivered'
        },
        fr: {
            site_name: 'PFG Chapati', home: 'Accueil', menu: 'Menu',
            why: 'Pourquoi PFG', vendors: 'Vendeurs',
            rider_dashboard: 'Tableau de bord livreur',
            vendor_dashboard: 'Tableau de bord vendeur',
            my_orders: 'Mes commandes', login: 'Se connecter',
            logout: 'Se déconnecter', profile: 'Profil',
            settings: 'Paramètres', order_now: 'Commander',
            hero_title: 'Chapatis frais livrés en 10 minutes',
            hero_subtitle: 'Commandez des chapatis chauds et délicieux de n\'importe où à Kampala et faites-les livrer à votre porte en seulement 10 minutes!',
            why_title: 'Pourquoi choisir PFG Chapati?',
            feature1_title: 'Livraison en 10 minutes',
            feature1_desc: 'Livraison garantie en 10 minutes partout à Kampala. Frais et chauds!',
            feature2_title: 'Ingrédients frais',
            feature2_desc: 'Nous vous connectons avec des artisans qui utilisent les ingrédients les plus frais.',
            feature3_title: 'Livraison gratuite',
            feature3_desc: 'Livraison gratuite pour les commandes de plus de 10 000 UGX. Sans frais cachés.',
            feature4_title: 'Variété de choix',
            feature4_desc: 'Du simple chapati au rolex et rolipizza – nous avons tout.',
            our_menu: 'Notre menu', breakfast: 'Petit-déjeuner',
            lunch: 'Déjeuner', dinner: 'Dîner', drinks: 'Boissons',
            find_vendors: 'Trouvez des vendeurs de chapati fiables à Kampala',
            vendors_sub: 'Frais, chauds et prêts — connectez-vous avec les meilleurs vendeurs locaux près de chez vous.',
            detect_location: 'Détecter ma position', search: 'Rechercher',
            your_cart: 'Votre panier', subtotal: 'Sous-total',
            discount: 'Remise', delivery_fee: 'Frais de livraison',
            total: 'Total', checkout: 'Commander',
            whatsapp_order: 'Commander via WhatsApp', call_now: 'Appeler',
            add_to_cart: 'Ajouter au panier',
            added_to_cart: '{name} ajouté au panier!',
            empty_cart: 'Votre panier est vide',
            delivery_details: 'Détails de livraison',
            payment_method: 'Méthode de paiement',
            cash_on_delivery: 'Paiement à la livraison',
            mobile_money: 'Mobile Money', credit_card: 'Carte de crédit',
            place_order: 'Passer la commande',
            order_placed: 'Commande passée avec succès!',
            order_failed: 'Échec de la commande',
            login_required: 'Veuillez vous connecter d\'abord',
            fill_details: 'Veuillez remplir tous les champs requis',
            points_earned: 'Vous avez {points} points ({beansCount} commandes Kikomando)',
            redeem: 'Échanger 100 points pour 1000 UGX de réduction',
            discount_applied: 'Réduction appliquée!',
            status_pending: 'En attente', status_assigned: 'Assigné',
            status_delivered: 'Livré', accept: 'Accepter',
            mark_delivered: 'Marquer comme livré', today_earnings: 'Gains du jour',
            total_earnings: 'Gains totaux', deliveries_today: 'Livraisons aujourd\'hui',
            rating: 'Évaluation', assigned_orders: 'Commandes assignées',
            delivery_history: 'Historique des livraisons',
            recent_orders: 'Commandes récentes', pending_orders: 'Commandes en attente',
            today_orders: 'Commandes aujourd\'hui', total_sales: 'Ventes totales',
            average_rating: 'Note moyenne', update_menu: 'Mettre à jour le menu',
            view_reviews: 'Voir les avis', earnings_report: 'Rapport de gains',
            full_name: 'Nom complet', phone_number: 'Numéro de téléphone',
            email: 'E-mail', default_address: 'Adresse de livraison par défaut',
            save_changes: 'Enregistrer', change_photo: 'Changer la photo',
            business_info: 'Informations commerciales',
            business_name: 'Nom de l\'entreprise',
            business_address: 'Adresse de l\'entreprise',
            business_hours: 'Heures d\'ouverture',
            vehicle_info: 'Informations sur le véhicule',
            vehicle_type: 'Type de véhicule', license_plate: 'Plaque d\'immatriculation',
            notifications: 'Notifications', push_notifications: 'Notifications push',
            sms_notifications: 'Notifications SMS',
            email_notifications: 'Notifications e-mail',
            language: 'Langue', payment_methods: 'Moyens de paiement',
            privacy_security: 'Confidentialité et sécurité',
            change_password: 'Changer le mot de passe',
            delete_account: 'Supprimer le compte',
            quick_links: 'Liens rapides', contact: 'Contact',
            privacy: 'Politique de confidentialité', terms: 'Conditions d\'utilisation',
            cookies: 'Politique de cookies',
            footer_desc: 'Relier les snacks et les clients à Kampala avec une garantie de 10 minutes.',
            download_app: 'Télécharger l\'app', all_orders: 'Toutes les commandes',
            cancelled: 'Annulé', track_order: 'Suivre votre commande',
            rider_location: 'Position du livreur', preparing: 'Préparation',
            out_for_delivery: 'En cours de livraison', delivered: 'Livré',
            accepted: 'Accepté', offline: 'Hors ligne', online: 'En ligne',
            customer: 'Client', rider: 'Livreur', vendor: 'Vendeur',
            save: 'Enregistrer', km_away: 'À {distance} km',
            location_detected: 'Position détectée!',
            location_failed: 'Impossible de détecter la position',
            login_email: 'Connexion avec Email', signup: 'S\'inscrire',
            confirm_password: 'Confirmer le mot de passe',
            forgot_password: 'Mot de passe oublié?',
            reset_password: 'Réinitialiser le mot de passe',
            no_account: 'Pas de compte? Inscrivez-vous',
            have_account: 'Déjà un compte? Connectez-vous',
            password_mismatch: 'Les mots de passe ne correspondent pas',
            login_success: 'Connecté avec succès!',
            signup_success: 'Compte créé avec succès!',
            reset_email_sent: 'Email de réinitialisation envoyé.',
            auth_modal_title: 'Connexion / Inscription', close: 'Fermer',
            verify_email: 'Veuillez vérifier votre email avant de vous connecter.',
            reset_instructions: 'Entrez votre email pour recevoir un lien de réinitialisation.',
            add_item: 'Ajouter un article', edit_item: 'Modifier',
            delete_item: 'Supprimer', item_name: 'Nom',
            item_description: 'Description', item_price: 'Prix',
            item_category: 'Catégorie', item_image: 'URL de l\'image',
            go_online: 'En ligne', go_offline: 'Hors ligne',
            accept_order: 'Accepter', order_accepted: 'Commande acceptée',
            order_delivered: 'Commande marquée comme livrée'
        }
    };
